language: ruby
sudo: false
rvm:
- 2.2
- 2.3.0
notifications:
  email:
    on_success: change
    on_failure: always
addons:
  code_climate:
    repo_token: 40f3b0db4e0b69a31588221de4aaca19db947e47c838f9eac9b6f4615cf92bab
script:
- bundle exec rubocop
- bundle exec rake spec
